// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMkAnIqVPDqQBO10gxytAY19HP7iqLOwA',
    appId: '1:460436985222:web:69dbf5034837ea8e064807',
    messagingSenderId: '460436985222',
    projectId: 'test-aed20',
    authDomain: 'test-aed20.firebaseapp.com',
    storageBucket: 'test-aed20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDepI7IH7taQ-6FoldIpLRkGrVoFJFegaA',
    appId: '1:460436985222:android:b926438ab854615a064807',
    messagingSenderId: '460436985222',
    projectId: 'test-aed20',
    storageBucket: 'test-aed20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB32rVRlqdXbrj4TGYMy-g9At1NpWIHTJg',
    appId: '1:460436985222:ios:1afd258f5dc232d7064807',
    messagingSenderId: '460436985222',
    projectId: 'test-aed20',
    storageBucket: 'test-aed20.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB32rVRlqdXbrj4TGYMy-g9At1NpWIHTJg',
    appId: '1:460436985222:ios:1afd258f5dc232d7064807',
    messagingSenderId: '460436985222',
    projectId: 'test-aed20',
    storageBucket: 'test-aed20.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMkAnIqVPDqQBO10gxytAY19HP7iqLOwA',
    appId: '1:460436985222:web:c638c640869d9117064807',
    messagingSenderId: '460436985222',
    projectId: 'test-aed20',
    authDomain: 'test-aed20.firebaseapp.com',
    storageBucket: 'test-aed20.firebasestorage.app',
  );
}
